[package]
name = "dumb-git-mirror"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
serde =  { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
tempfile = "3.19.1"
